name: Run tests pipenv

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python 3.7.5
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.5'
      - name: Install dependencies using pipenv
        run: |
          python -m pip install pipenv
          pipenv install
      - name: run tests
        run: python -m unittest discover ./tests
