name: Run tests pipenv

on: push

jobs:
  run-shell-command:
    runs-on: debian-11
    steps:
      - uses: actions/checkout@v2
      - name: Setup python 3.8.16
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.16'
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Install dependencies using pipenv
        run: pipenv sync --dev
      - name: run tests
        run: pipenv run python -m pytest
