name: Run tests

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python 3.7.3
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.3'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run tests
        run: python -m unittest discover ./tests
